#!/bin/bash
#
# set -x
#

NODE=1998
# get node number
#source /usr/local/KF5VH/N1NODE

WX=/usr/local/AUTOSKY
OFILE='KCXW.xml'     #Set To Local Reporting Station (this is an airport)
NFILE='now.txt1'
#
cd $WX ;
#
# PULL THE INFORMATION FROM NWS
/usr/bin/wget --no-check-certificate  w1.weather.gov/xml/current_obs/$OFILE  2>/dev/null
#
# COPY THE WEIRD NAMED FILE TO SOMETHING NORMAL
/bin/cp -f $OFILE $NFILE
# 
# REMOVE the WEIRDLY NAMED FILE
/bin/rm -f $OFILE
#
# RESET FILE NAMES
OFILE='now.txt1'
TFILE='now.txtt'
NFILE='now.txt2'
#
# REMOVE THE NEW FILE NAME and TEMP FILE NAME
/bin/rm -f $NFILE $TFILE
# 
# COPY THE EXISTING (OLD) TEXT FILE TO THE TEMP FILE
/bin/cp -f $OFILE $TFILE
#
# COPY ONLY DESIRED SECTIONS OF MANY
#  FROM THE TEMP FILE TO THE NEW FILE
/bin/egrep -i "location>|observation_time>|weather>|temp_f>|relative_humidity>|wind_string>" < $TFILE > $NFILE
/bin/egrep -i "pressure_in>|dewpoint_f>|heat_index_f>|visibility_mi>" < $TFILE >> $NFILE
#
# RESET FILE NAMES AGAIN
OFILE='now.txt2'
TFILE='now.txtt'
NFILE='now.txt3'
#
/bin/rm -f $NFILE $TFILE ;
/bin/cp -f $OFILE $TFILE ;
#
# ESTABLISH BREAKS BETWEEN SEGMENTS
/bin/sed -i 's%</.*>% , %' $TFILE
/bin/sed -i '$s%$% END OF REPORT %' $TFILE

# CHANGE STUFF
/bin/sed -i 's/Lafayette, Lafayette /Lafayette /' $TFILE;
/bin/sed -i 's/(.*KT)/ /' $TFILE;
/bin/sed -i 's/, LA/ /' $TFILE;
/bin/sed -i 's/<location>/From the /' $TFILE;
/bin/sed -i 's/<observation_time>/ /' $TFILE;
/bin/sed -i 's/<weather>/The weather is /' $TFILE
/bin/sed -i 's/<temp_f>/The current temperature is /' $TFILE
/bin/sed -i 's/<relative_humidity>/Relative Humidity /' $TFILE
/bin/sed -i 's/<wind_string>/Winds are /' $TFILE
/bin/sed -i 's/ MPH / miles per hour /' $TFILE
/bin/sed -i 's/<pressure_in>/Pressure in inches /' $TFILE
/bin/sed -i 's/<dewpoint_f>/The dew point is /' $TFILE
/bin/sed -i 's/\.00 / /' $TFILE
/bin/sed -i 's/<visibility_mi>/and visibility is /' $TFILE
/bin/sed -i 's/<heat_index_f>/The heat index is /' $TFILE
/bin/sed -i 's/m CDT / m Central Time /' $TFILE
#
#GET RID OF SED TMP FILES
/bin/rm -f sed*
#
cp -f $TFILE $NFILE
#
/usr/bin/text2wave -F 8000 -otype ulaw ${WX}/${NFILE} -o ${WX}/now.ulaw
#
/usr/sbin/asterisk -rvx "rpt localplay $NODE ${WX}/now" 

# DIAG - Text Script
# cat now.txt3
