#!/bin/bash
#
# set -x
#

# NODE=42315
# get the node number
source /usr/local/KF5VH/N1NODE

WX=/usr/local/AUTOSKY
OFILE='wwaatmget.php?x=LAC055&y=0'
NFILE='saysum.txt1'
#
cd $WX ;
#
# PULL THE INFORMATION FROM NWS
/usr/bin/wget --no-check-certificate  alerts.weather.gov/cap/$OFILE  2>/dev/null
#
# COPY THE WEIRD NAMED FILE TO SOMETHING NORMAL
/bin/cp -f $OFILE $NFILE
# 
# REMOVE the WEIRDLY NAMED FILE
/bin/rm -f $OFILE
#
#
OFILE='saysum.txt1'
TFILE='saysum.txtt'
NFILE='saysum.txt2'
#
#
# REMOVE THE NEW FILE NAME and TEMP FILE NAME
/bin/rm -f $NFILE $TFILE
# 
# COPY THE EXISTING (OLD) TEXT FILE TO THE TEMP FILE
/bin/cp -f $OFILE $TFILE
#
# COPY ONLY ONE SECTION (can be multiple) OF MANY
#   FROM THE TEMP FILE TO THE NEW FILE
/bin/egrep "summary" < $TFILE > $NFILE
#
/usr/bin/wc -l < $NFILE > saysum.wc
RESULT=`/bin/cat saysum.wc`
#
# DIAG
# echo $RESULT
#
if [ $RESULT -eq 0 ] ; then
     echo "There are no weather alerts at this time." > saysum.bo
     /usr/bin/text2wave -F 8000 -otype ulaw $WX/saysum.bo -o $WX/saysum.ulaw
     sync
     /usr/sbin/asterisk -rvx "rpt localplay $NODE $WX/saysum" 
     sync
     exit 0
fi
#
#
OFILE='saysum.txt2'
TFILE='saysum.txtt'
NFILE='saysum.txt3'
#
/bin/rm -f $WX/$NFILE $WX/$TFILE ;
/bin/cp -f $WX/$OFILE $WX/$TFILE ;

# ESTABLISH BREAKS BETWEEN SEGMENTS
/bin/sed -i 's%</summary>% , BREAK , %' $WX/$TFILE
/bin/sed -i 's%<summary>%%' $WX/$TFILE

# REMOVE COUNTY CODE
/bin/sed -i 's/(LAC055)//' $WX/$TFILE;

# CHANGE NWS to N-W-S
# /bin/sed -i 's/National Weather Service/ N-W-S /' $WX/$TFILE;
/bin/sed -i 's/ by NWS/ /' $WX/$TFILE;

# CHANGE TRAILING ", BREAK ," to ", END OF MESSAGE "
/bin/sed -i '$s% , BREAK ,%. , END OF REPORT%' $WX/$TFILE

# CHANGE "..." to " , "
/bin/sed -i 's/\.\.\./ , /g' $WX/$TFILE;

# CHANGE "C[SD]T" to "C-[SD]-T"
/bin/sed -i 's/CDT/C-D-T/g;s/CST/C-S-T/g' $WX/$TFILE;

# CHANGE " mph" to " miles per hour"
/bin/sed -i 's/\ mph/\ miles per hour/g' $WX/$TFILE;

#GET RID OF SED TMP FILES
/bin/rm -f sed*

cp -f $WX/$TFILE $WX/$NFILE
/usr/bin/text2wave -F 8000 -otype ulaw $WX/$NFILE -o $WX/saysum.ulaw
sync
/usr/sbin/asterisk -rvx "rpt localplay $NODE $WX/saysum" 

