#!/bin/bash

# set -x

# First obtain a location code from: https://weather.codes/search/

# Insert your location. For example LOXX0001 is a location code for Bratislava, Slovakia
# location="LOXX0001"
location="USLA0261"	#code for you location
nlocation="Lafayette"
WORK=/usr/local/AUTOSKY
TEXT=$WORK/srs.txt
TALKIT=$WORK/TALKIT/Talkit

cd $WORK

# Obtain sunrise and sunset raw data from weather.com
sun_times=$( lynx --dump  https://weather.com/weather/today/l/$location | grep "\* Sun" | sed "s/[[:alpha:]]//g;s/*//" )
# Extract sunrise and sunset times and convert to 24 hour format
sunrise=$(date --date="`echo $sun_times | awk '{ print $1}'` AM" +%R)
sunset=$(date --date="`echo $sun_times | awk '{ print $2}'` PM" +%R)

# clear the text file
rm -f $TEXT

# build the text file
echo "In  $nlocation , "                >  $TEXT
echo "Sunrise is at $sunrise A M , and" >> $TEXT
echo "Sunset is at  $sunset P M ."      >> $TEXT

# now call Talkit
$TALKIT `cat $TEXT`
