#!/bin/bash
#
# Source Some Info
source /home/repeater/WRKF394-utils/AUTOSKY/autoskywarn.conf

# Where the text will live
NFILE="${BASEDIR}/TALKIT/talkit.txt"
UFILE="${BASEDIR}/TALKIT/talkit.ulaw"

cd $BASEDIR

# Make some space
$RM -f $NFILE $UFILE

if [ $# -lt 1 ] ; then
   echo "talkit: You have to say something!"
   exit
fi

/bin/echo $@ > $NFILE

/usr/bin/text2wave -F 8000 -otype ulaw $NFILE -o $UFILE
/usr/sbin/asterisk -rvx "rpt localplay $NODE ${UFILE%.ulaw}" 

