#!/bin/bash
#
# Asterisk Echolink lookup script by KF5VH on 3/25/2017
# Usage: echolookup  [lookup-data]
#

# set -x

if [ "$1" == "" ] ; then
echo "Usage: echolookup [nodename|callsign|ipaddr]"
exit -1
fi

asterisk -rx "echolink dbdump" | grep -i $1

exit 0
