#! /bin/bash
#

# set -x

# all work done in /tmp
cd /tmp

# remove files used
rm -f x[123456789]

# get file names
find /usr/local -print > x1
find /etc/asterisk -print >> x1
find /var/lib/asterisk -print >> x1

# for each filename, glean what type of file
while IFS="" read -r p || [ -n "$p" ]
do
     file $p >> x2
done < x1

# cull out the shell scripts
egrep "shell script" < x2 > x3

# copy the x3 file via sed
# grab just the file names
sed -e "s/:.*$//" < x3 > x4

# read x4 and grep for distribution
# node number (42315)
while IFS="" read -r p || [ -n "$p" ]
do
     grep -H 42315 $p >> x5
done < x4

echo " "
echo OUTPUT FILE IS IN /tmp/x5
