#!/bin/bash
#
##################################################################
# KF5VH-PLAY AUTOSKYWARN WAV FILE by KF5VH
##################################################################
#

# set -x

# OBTAIN STANDARD AUTOSKYWARN VARIABLES
source /usr/local/AUTOSKY/autoskywarn.conf

WORK=${BASEDIR}/SOUNDS
PREFIX="asn"

cd $WORK

if [ $# -ne 1 ]; then
  /bin/echo "Usage: playasn number-of-AutoSkyWarn-announcement-to-play"
  exit -1
fi

NN="$1"

/usr/sbin/asterisk -rx "rpt localplay $NODE ${WORK}/${PREFIX}${NN} " 2>>/dev/null

exit 0

